### ISSUE TITLE
Changes to how things are loaded to ease development

### ISSUE THREAD

**Issue by ajoslin** [ngbp/ngbp#34]
So I've built a few projects now starting with the ngBoilerplate structure, and I've ended up doing it a bit different to make it easier during development.

The main difference is that during development, I don't concatenate everything.  

I use a foreach loop in the index.html to dynamically load js/css:

``` html
  <% distCss.forEach(function(file) { %>
  <link rel="stylesheet" href="<%= file %>"></script>
  <% }); %>
  <% distJs.forEach(function(file) { %>
  <script src="<%= file %>"></script>
  <% }); %>
```

I have a components list in my Gruntfile to ensure load order is correct:

``` js
  //List all our files we'll be using.  We list components in the order
  //that they need to be loaded.
  files: {
    js: ['src/**/*.js', '!src/**/*.spec.js'],
    tpl: ['src/**/*.tpl.html'],
    test: ['src/**/*.spec.js'],
    styl: ['stylus/main.styl'],
    component: [
      'components/appframework/jq.mobi.js',
      'components/angular-unstable/angular.js',
      'components/angular-mobile-nav/mobile-nav.js',
      'components/angular-collection/angular-collection.js',
      'components/promise-tracker/promise-tracker.js',
      'components/Snap.js/snap.js'
    ]
  },
```

Then I have a simple build step which builds `distJs` and `distCss`:

``` js
grunt.registerTask('build', 'Build all files to dist, build file list for index.html', function() {
  var jsFiles = grunt.config('files.component');
  jsFiles = jsFiles.concat(grunt.file.expand(grunt.config('files.js')).map(function(file) {
    return file.replace('src/', '');
  }));
  jsFiles.push(grunt.config('html2js.files.dest').replace('dist/',''));

  grunt.config('distJs', jsFiles);
  grunt.config('distCss', getCssFiles());

  grunt.task.run(['jshint', 'clean', 'html2js', 'stylus', 'copy']);
});
```

Now during development, I simply copy `components/` and `src/` javascript files into `dist/`.  Then I just load all of the files into index.html.  This makes it so errors appear in the correct files and it's really easy to do debugging, breakpoints, etc.

Then I have a `build-production` step where I just concatenate everything, ngmin it, and uglify it into one css file and one js file.

If you're interested in this, I could setup a pull request.  I would also upgrade to grunt-karma.

**Comment by joshdmiller** [comment]
Hey @ajoslin! I'm glad you opened this as I've been thinking about some of the very same things lately (I alluded to them in #24 under the guise of efficiency). I also think there's some broader work to be done in distinguishing between development-related tasks and distribution/production-related tasks.

I made some pretty heavy changes to the Gruntfile recently (see 864c2656f79b11081c917f566549ed19fa33b1ea for the most major) that I think will make your proposal easier. It's already running `grunt-karma`, too.  `src/components` is now all user-created, though still drag-and-drop, and third-party components are stored in `vendor/` - so the old `vendor/` is now `build/` and the old `build/` is now `grunt-tasks/` - so that those components that can be are managed with Bower. The point is that the Bower components are now listed manually in a Grunt config variable very similar to your `files.components` variable above (see [here](https://github.com/joshdmiller/ng-boilerplate/blob/master/Gruntfile.js#L84)).

So I see splitting the `build` task into `build` and `compile` tasks, the former handling the correct copying, linting, testing, and recess and the latter handling annotation, concatenation, and uglification. These should probably go to two different directories: the former to `dev/` and the latter to `build/`. The `default` task runs both, but the `watch` tasks don't run the `compile` tasks.

In the `build` task, the grunt config would be loaded with _all_ JavaScript sources, while the `compile` task only loads the single concatenated source, so the index.html ends up with the correct files regardless of the build step.

What do you think?

**Comment by ajoslin** [comment]
Hey Josh! Glad you've been thinking about this too.  This seems like the best solution for sure, we should implement it.  

`compile` is a great name for this :-) .. I was looking for a verb, I hated calling it production.  And since we have a `compile` step.. perhaps like `bin` is a good name for the compiled folder :D

**Comment by ajoslin** [comment]
I can open a PR in the next few days, unless you wanna go for it.

**Comment by joshdmiller** [comment]
`bin/` is a great name for the compiled folder. Like the good ol' days of statically-typed, compiled code. :+1:

I'm also going to place all of these on a `v0.3-wip` branch so we don't have to work on documentation until the dust settles.

For the file array to populate `index.html`, I think it could be as simple as having a property for the multi-task (to replace the current `index` task):

``` js
index: {
  build: {
    dir: '<%= build_dir %>',
    scripts: [
      '<%= vendor_files.js %>',
      '<%= build_dir %>/html2js/**/*.js',
      '<%= app_files.js %>'
    ]
  },
  compile: 
    dir: '<%= bin_dir %>',
    scripts: [
      'assets/<%= pkg.name %>.min.js'
    ]
  }
},
```

And the multi-task would assign the grunt config property its file list and then compile the template. So the exact same code could serve both purposes. Something as simple as this:

``` js
grunt.registerMultiTask( 'index', 'Process index.html template', function () {
  var files = this.data.scripts;
  grunt.file.copy('src/index.html', this.data.dir + '/index.html', {
    process: function (contents, path) {
      return grunt.template.process( contents, {
        data: { scripts: files }
      });
    }
  });
});
```

And then in `index.html`:

``` html
<% scripts.forEach(function(file) { %>
  <script src="<%= file %>"></script>
<% }); %>
```

**Todo:**
- [ ] Rename the Grunt config `src` to `app_files` and `vendor` to `vendor_files` to be more descriptive
- [ ] Remove the statically-included AngularJS files and replace them with Bower dependencies (otherwise we can't control the order in which `angular.js` loads, which will cause jQuery problems for those who use it)
- [ ] Split out `build` and `compile` tasks
- [ ] Add per-source inclusion to `index.html` to ease debugging
- [ ] Update docs...or more likely rewrite massive chunks of them...

If you have time, a PR for any of this would be **awesome**.

**Comment by ajoslin** [comment]
Actually working on this now, I'm working on a gruntfile for a current project :-)

What if we renamed `src/components` to `src/common`?  Since bower came around, I think of components as third party.  Plus, common is easier to type.

Then we could rename `vendor` back to `components`, since that's the bower default.

**Comment by joshdmiller** [comment]
Sweet. :-)

In discussions separate from ngBoilerplate, I've noticed the confusion with how Bower uses the term "components", so I don't object to changing `src/components/` to `src/common`. I also think it's a little more descriptive ... and easier to type.

As for `vendor/`, I'd prefer to keep that as is. I do not think the term "components" is very descriptive because everything is a "component"; the difference between `src/` and `vendor/` is that the latter comes from third parties. Even though "components" is the Bower default, I'm willing to break with convention a little bit here - and it's easy enough for someone to change in their own project if they really want to. 

[rant]
Besides, I've bent over enough for Bower; it's a cool concept, but thus far poorly executed when it comes to anything except jQuery plugins. There needs to be standardization like every other package manager has, from NPM to Gem to apt. I've heard the team is working on this, but in the meantime, it's a bit of a kluge. E.g. someone added my `angular-placeholders` library to it uncompiled! That library, like many (most?) AngularJS-based libraries, is useless before it's built. But now the name's taken and I have to hassle to get it removed. Not to mention that I then have to maintain two separate repositories just to make it work with Bower. I have to duplicate information between the `bower.json` and `package.json` files. Etc.

Bower has a lot of potential, so I have placed my faith in the team and included it. But "components" doesn't make any sense to me in context. I don't always have an opinion, but when I do... :-)
[/rant]

**Comment by jcamorgan** [comment]
Hi Guys!
Brilliant what you are doing here! 
@ajoslin Any chance you you posting your Gruntfile... I'm a bit on a newbie to grunt and am getting some errors when implementing your code. 
...\ng-boilerplate\src>grunt 
Running "build" task  
Warning: Cannot call method 'replace' of undefined Use --force to continue.  
Aborted due to warnings.           

Thanks!

**Comment by ajoslin** [comment]
Hi @jcamorgan, I opened a pull request: #35.  I'll close this for now and we can move discussion there.

**Comment by joshdmiller** [comment]
I'll go ahead close this. But we're definitely not done just yet - _this_ party's going all night long at Club #35.
